name: âš™ï¸ CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  redwood-ci:
    name: ğŸŒ² Redwood CI
    runs-on: ubuntu-latest
    steps:
      - name: ğŸŒ² Redwood CI
        uses: redwoodjs/project-ci-action@v0.1.1

      - name: ğŸ­ Playwright E2E Tests
        run: npx playwright test e2e
