name: âš™ï¸ CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  redwood-ci:
    name: ðŸŒ² Redwood CI
    runs-on: ubuntu-latest
    steps:
      - name: ðŸŒ² Redwood CI
        uses: redwoodjs/project-ci-action@main

      - run: npx playwright install --with-deps

      - name: Write vars to .env
        run: |
          echo 'DATABASE_URL=postgresql://test:password@localhost:5432/test' >> .env
          echo 'STRIPE_PUBLISHABLE_KEY=${{ secrets.STRIPE_PUBLISHABLE_KEY }}' >> .env
          echo 'STRIPE_SECRET_KEY=${{ secrets.STRIPE_SECRET_KEY }}' >> .env
          echo 'SESSION_SECRET=${{ secrets.SESSION_SECRET }}' >> .env
          echo 'STRIPE_WEBHOOK_KEY=${{ secrets.STRIPE_WEBHOOK_KEY }}' >> .env

      - name: ðŸŽ­ Playwright E2E Tests
        run: npx playwright test e2e

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results/
          retention-days: 30

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: example-store-e2e-web-server.log
          path:  /tmp/example-store-e2e-web-server.log
          retention-days: 30


