name: âš™ï¸ CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  redwood-ci:
    name: ğŸŒ² Redwood CI
    runs-on: ubuntu-latest
    steps:
      - name: ğŸŒ² Redwood CI
        uses: redwoodjs/project-ci-action@v0.1.1

      - run: npx playwright install --with-deps

      - name: ğŸ­ Playwright E2E Tests
        run: npx playwright test e2e
        env:
          DATABASE_URL: postgresql://test:password@localhost:5432/test
          STRIPE_PK: ${{ secrets.STRIPE_PK }}
          STRIPE_SK: ${{ secrets.STRIPE_SK }}
          SESSION_SECRET: ${{ secrets.SESSION_SECRET }}


